# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class Auto:
    watch: bool
    git: bool
    path: list[str]
    regex: list[str]
    always: bool

class Command:
    id: str
    name: str
    cmd: str
    cwd: str
    interactive: bool
    auto: Auto

class CommandGroup:
    id: str
    name: str
    auto: Auto
    cwd: str
    commands: list[Command]
    children: list[CommandGroup]

class FnugCore:
    config: CommandGroup
    cwd: typing.Any
    def __new__(cls,config_file = ...): ...
    def all_commands(self) -> list[Command]:
        ...

    def commands_with_git_changes(self) -> list[Command]:
        ...


