# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import os
import pathlib
import typing

class Auto:
    watch: bool
    git: bool
    path: list[str]
    regex: list[str]
    always: bool
    def __new__(cls,watch = ...,git = ...,path = ...,regex = ...,always = ...): ...

class Command:
    id: str
    name: str
    cmd: str
    cwd: str
    interactive: bool
    auto: Auto
    def __new__(cls,name,cmd,id = ...,cwd = ...,interactive = ...,auto = ...): ...
    def __eq__(self, other:Command) -> bool:
        ...


class CommandGroup:
    id: str
    name: str
    auto: Auto
    cwd: str
    commands: list[Command]
    children: list[CommandGroup]
    def __new__(cls,name,id = ...,auto = ...,cwd = ...,commands = ...,children = ...): ...

class FnugCore:
    config: CommandGroup
    cwd: typing.Any
    @classmethod
    def from_group(cls, command_group,cwd) -> FnugCore:
        ...

    @classmethod
    def from_config_file(cls, config_file = ...) -> FnugCore:
        ...

    def all_commands(self) -> list[Command]:
        ...

    def commands_with_git_changes(self) -> list[Command]:
        ...


