fnug_version: 0.1.0
name: fnug
children:
  - name: fnug
    autorun:
      watch: true
      git: true
      path:
        - "./src/fnug"
      regex:
        - "\\.py$"
    commands:
      - name: pyright
        cmd: rye run pyright src
      - name: lint
        cmd: rye run ruff --fix .
      - name: format
        cmd: rye run ruff format .
      - name: test
        cmd: rye run test
  - name: debug
    commands:
      - name: htop
        cmd: htop
        interactive: true
      - name: recursive?!
        cmd: fnug
        interactive: true
      - name: A very very very long file
        cmd: |
          cat src/fnug/terminal_emulator.py
          cat src/fnug/terminal_emulator.py
          cat src/fnug/terminal_emulator.py
    children:
      - name: nested-autorun
        autorun:
          always: true
        commands:
          - name: test-autorun
            cmd: cat src/fnug/terminal_emulator.py
          - name: test-not-autorun
            autorun:
              always: false
            cmd: cat src/fnug/terminal_emulator.py
      - name: not-expanded
        autorun:
          always: false
        commands:
          - name: test-not-expanded
            cmd: cat src/fnug/terminal_emulator.py
