fnug_version: 0.1.0
name: fnug
children:
  - name: rust
    auto:
      watch: true
      git: true
      path:
        - "./src"
      regex:
        - "\\.rs$"
    commands:
      - name: fmt
        cmd: cargo fmt
      - name: test
        cmd: cargo test
      - name: clippy
        cmd: cargo clippy --fix --allow-dirty --allow-staged
      - name: cwd
        cmd: pwd
  - name: debug
    commands:
      - name: htop
        cmd: htop
      - name: recursive?!
        cmd: cargo run --bin fnug
      - name: A very very very long name
        cmd: cat src/pty/terminal.rs
      - name: always-fails
        cmd: exit 1
    children:
      - name: nested-auto
        auto:
          always: true
        commands:
          - name: test-auto
            cmd: cat src/pty/terminal.rs
          - name: test-not-auto
            auto:
              always: false
            cmd: cat src/pty/terminal.rs
      - name: not-expanded
        auto:
          always: false
        commands:
          - name: test-not-expanded
            cmd: cat src/pty/terminal.rs
