fnug_version: 0.1.0
name: fnug
workspace: true
children:
  - name: rust
    auto:
      watch: true
      git: true
      path:
        - "./src"
      regex:
        - "\\.rs$"
    commands:
      - name: lockfile
        id: rust-lockfile
        cmd: cargo check --locked
      - name: fmt
        id: rust-fmt
        cmd: cargo fmt
      - name: test
        cmd: cargo test
      - name: clippy fix
        id: rust-clippy-fix
        cmd: cargo clippy --fix --allow-dirty --allow-staged
        depends_on:
          - rust-fmt
      - name: clippy check
        cmd: cargo clippy -- -D warnings
        depends_on:
          - rust-clippy-fix
      - name: cwd
        cmd: pwd
  - name: python
    auto:
      watch: true
      git: true
      path:
        - "./python"
      regex:
        - "\\.py$"
    commands:
      - name: ruff check
        id: python-ruff-check
        cmd: ruff check python/
      - name: ruff format
        cmd: ruff format --check python/
  - name: nix
    auto:
      watch: true
      git: true
      path:
        - "."
      regex:
        - "\\.nix$"
    commands:
      - name: fmt
        cmd: alejandra --check .
      - name: statix
        cmd: statix check .
      - name: deadnix
        cmd: deadnix .
  - name: docs
    auto:
      watch: true
      git: true
    commands:
      - name: vhs
        cmd: vhs docs/demo.tape
        auto:
          path:
            - "./docs/demo.tape"
          check: false
