fnug_version: 0.1.0
name: fnug
children:
  - name: fnug
    auto:
      watch: true
      git: true
      path:
        - "./src/fnug"
      regex:
        - "\\.py$"
    commands:
      - name: pyright
        cmd: uv run pyright src
      - name: lint
        cmd: uv run ruff check --fix .
      - name: format
        cmd: uv run ruff format .
      - name: test
        cmd: uv run pytest tests
  - name: rust
    cwd: "./rust"
    auto:
      watch: true
      git: true
      path:
        - "./src"
      regex:
        - "\\.rs$"
    commands:
      - name: fmt
        cmd: cargo fmt
      - name: test
        cmd: cargo test --no-default-features
      - name: clippy
        cmd: cargo clippy --fix --allow-dirty --allow-staged
      - name: stub gen
        cmd: cargo run --bin stub_gen --features stub_gen
      - name: cwd
        cmd: pwd
  - name: debug
    commands:
      - name: htop
        cmd: htop
        interactive: true
      - name: recursive?!
        cmd: fnug
        interactive: true
      - name: A very very very long name
        cmd: cat rust/src/pty/terminal.rs
    children:
      - name: nested-auto
        auto:
          always: true
        commands:
          - name: test-auto
            cmd: cat rust/src/pty/terminal.rs
          - name: test-not-auto
            auto:
              always: false
            cmd: cat rust/src/pty/terminal.rs
      - name: not-expanded
        auto:
          always: false
        commands:
          - name: test-not-expanded
            cmd: cat rust/src/pty/terminal.rs
