fnug_version: 0.1.0
name: fnug
children:
  - name: lint
    autorun:
      watch: true
      git: true
      path:
        - "./src/fnug"
      regex:
        - "\\.py$"
    commands:
      - name: black
        cmd: rye run black .
      - name: pyright
        cmd: rye run pyright src
      - name: ruff
        cmd: rye run ruff --fix src
  - name: fnug-test
    commands:
      - name: htop
        cmd: htop
      - name: recursive?!
        cmd: fnug
      - name: A very very very long file
        cmd: cat src/fnug/terminal_emulator.py ; cat src/fnug/terminal_emulator.py ; cat
          src/fnug/terminal_emulator.py
    children:
      - name: nested-autorun
        autorun:
          always: true
        commands:
          - name: test-autorun
            cmd: cat src/fnug/terminal_emulator.py
          - name: test-not-autorun
            autorun:
              always: false
            cmd: cat src/fnug/terminal_emulator.py