fnug_version: 0.1.0
name: fnug
children:
  - name: rust
    auto:
      watch: true
      git: true
      path:
        - "./src"
      regex:
        - "\\.rs$"
    commands:
      - name: fmt
        id: rust-fmt
        cmd: cargo fmt
      - name: test
        cmd: cargo test
      - name: clippy fix
        id: rust-clippy-fix
        cmd: cargo clippy --fix --allow-dirty --allow-staged
        depends_on:
          - rust-fmt
      - name: clippy check
        cmd: cargo clippy -- -D warnings
        depends_on:
          - rust-clippy-fix
      - name: cwd
        cmd: pwd
  - name: python
    auto:
      watch: true
      git: true
      path:
        - "./python"
      regex:
        - "\\.py$"
    commands:
      - name: ruff check
        id: python-ruff-check
        cmd: ruff check python/
      - name: ruff format
        cmd: ruff format --check python/
  - name: nix
    auto:
      watch: true
      git: true
      path:
        - "."
      regex:
        - "\\.nix$"
    commands:
      - name: fmt
        cmd: alejandra --check .
      - name: statix
        cmd: statix check .
      - name: deadnix
        cmd: deadnix .
  - name: debug
    commands:
      - name: htop
        cmd: htop
      - name: recursive?!
        cmd: cargo run --bin fnug
      - name: A very very very long name
        cmd: cat src/pty/terminal.rs
      - name: always-fails
        cmd: exit 1
    children:
      - name: nested-auto
        auto:
          always: true
        commands:
          - name: test-auto
            cmd: cat src/pty/terminal.rs
          - name: test-not-auto
            auto:
              always: false
            cmd: cat src/pty/terminal.rs
      - name: not-expanded
        auto:
          always: false
        commands:
          - name: test-not-expanded
            cmd: cat src/pty/terminal.rs
